version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vsmart
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/vsmart?schema=public
      - PORT=4000
      - JWT_SECRET=devsecret
      - LOCAL_MOCK_MODE=true
    working_dir: /usr/src/app
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy || true && npm run dev"
    ports:
      - "4000:4000"

volumes:
  pgdata:
